// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://uhldzobbbqeojcudnjis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVobGR6b2JiYnFlb2pjdWRuamlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTYzNTMsImV4cCI6MjA3MDIzMjM1M30.SgSIEfO6SVtY9ew1EMRShTY_zckrrq8zh-1lNUEHyPM";

console.log('Supabase config:', { 
  url: SUPABASE_URL, 
  key: SUPABASE_PUBLISHABLE_KEY?.substring(0, 20) + '...' 
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});